nelmio_api_doc:
    documentation:
        info:
            title: Contact Form API
            description: API dla formularza kontaktowego
            version: 1.0.0
        servers:
            - url: 'http://localhost:8000'
              description: 'Local development server'
    html_config:
        assets_mode: cdn
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc)

